#!/data/data/com.termux/files/usr/bin/sh

exec 2>&1
config="$HOME/.config/bks/nginx.conf"
while [ ! -f "$config" ]; do
    sleep 5
done
exec nginx \
    -p "$HOME/.local/state/bks/nginx/" \
    -c "$config" \
    -g 'daemon off;'
