package com.autoaccounting.backend.ai

import com.autoaccounting.backend.Migration
import com.autoaccounting.backend.jdbcConnection
import com.autoaccounting.backend.runMigrations

class JdbcAiCategorizationLogStore(
    private val jdbcUrl: String,
    private val username: String = "",
    private val password: String = ""
) : AiCategorizationLogStore {
    init {
        runMigrations(jdbcUrl, username, password, aiLogMigrations)
    }

    override fun insertLog(log: StoredAiCategorizationLog) {
        connection().use { connection ->
            connection.prepareStatement(
                """
                INSERT INTO ai_categorization_logs (
                    account_phone, merchant_title, source_label,
                    transaction_kind, amount_range_label,
                    suggested_category, confidence_label, explanation,
                    created_at_millis
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """.trimIndent()
            ).use { statement ->
                if (log.accountPhone == null) {
                    statement.setNull(1, java.sql.Types.VARCHAR)
                } else {
                    statement.setString(1, log.accountPhone)
                }
                statement.setString(2, log.merchantTitle)
                statement.setString(3, log.sourceLabel)
                statement.setString(4, log.transactionKind)
                statement.setString(5, log.amountRangeLabel)
                statement.setString(6, log.suggestedCategory)
                statement.setString(7, log.confidenceLabel)
                statement.setString(8, log.explanation)
                statement.setLong(9, log.createdAtMillis)
                statement.executeUpdate()
            }
        }
    }

    override fun logsForAccount(phone: String): List<StoredAiCategorizationLog> = connection().use { connection ->
        connection.prepareStatement(
            """
            SELECT id, account_phone, merchant_title, source_label,
                   transaction_kind, amount_range_label,
                   suggested_category, confidence_label, explanation,
                   created_at_millis
            FROM ai_categorization_logs
            WHERE account_phone = ?
            ORDER BY id
            """.trimIndent()
        ).use { statement ->
            statement.setString(1, phone)
            statement.executeQuery().use { rs ->
                buildList {
                    while (rs.next()) add(rs.toStoredLog())
                }
            }
        }
    }

    override fun allLogs(): List<StoredAiCategorizationLog> = connection().use { connection ->
        connection.prepareStatement(
            """
            SELECT id, account_phone, merchant_title, source_label,
                   transaction_kind, amount_range_label,
                   suggested_category, confidence_label, explanation,
                   created_at_millis
            FROM ai_categorization_logs
            ORDER BY id
            """.trimIndent()
        ).use { statement ->
            statement.executeQuery().use { rs ->
                buildList {
                    while (rs.next()) add(rs.toStoredLog())
                }
            }
        }
    }

    override fun deleteLogsForAccount(phone: String) {
        connection().use { connection ->
            connection.prepareStatement(
                "DELETE FROM ai_categorization_logs WHERE account_phone = ?"
            ).use { statement ->
                statement.setString(1, phone)
                statement.executeUpdate()
            }
        }
    }

    private fun connection() = jdbcConnection(jdbcUrl, username, password)
}

private fun java.sql.ResultSet.toStoredLog(): StoredAiCategorizationLog {
    return StoredAiCategorizationLog(
        id = getLong("id"),
        accountPhone = getString("account_phone"),
        merchantTitle = getString("merchant_title"),
        sourceLabel = getString("source_label"),
        transactionKind = getString("transaction_kind"),
        amountRangeLabel = getString("amount_range_label"),
        suggestedCategory = getString("suggested_category"),
        confidenceLabel = getString("confidence_label"),
        explanation = getString("explanation"),
        createdAtMillis = getLong("created_at_millis")
    )
}

private val aiLogMigrations = listOf(
    Migration(
        version = 3,
        statements = listOf(
            """
            CREATE TABLE IF NOT EXISTS ai_categorization_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                account_phone VARCHAR(32),
                merchant_title TEXT NOT NULL,
                source_label TEXT NOT NULL,
                transaction_kind TEXT NOT NULL,
                amount_range_label TEXT NOT NULL,
                suggested_category TEXT NOT NULL,
                confidence_label TEXT NOT NULL,
                explanation TEXT NOT NULL,
                created_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            CREATE INDEX IF NOT EXISTS ai_categorization_logs_phone_idx
            ON ai_categorization_logs(account_phone)
            """.trimIndent()
        )
    )
)
