@file:Suppress("MatchingDeclarationName", "NestedBlockDepth")

package com.autoaccounting.backend

import java.sql.Connection
import java.sql.DriverManager

data class Migration(
    val version: Int,
    val statements: List<String>
)

fun runMigrations(
    jdbcUrl: String,
    username: String = "",
    password: String = "",
    migrations: List<Migration>
) {
    jdbcConnection(jdbcUrl, username, password).use { connection ->
        connection.createStatement().use { statement ->
            statement.execute(
                """
                CREATE TABLE IF NOT EXISTS schema_migrations (
                    version INTEGER PRIMARY KEY,
                    applied_at_millis BIGINT NOT NULL
                )
                """.trimIndent()
            )
        }
        val applied = connection.createStatement().use { statement ->
            statement.executeQuery("SELECT version FROM schema_migrations").use { rs ->
                buildSet {
                    while (rs.next()) add(rs.getInt("version"))
                }
            }
        }
        migrations.filter { it.version !in applied }.forEach { migration ->
            connection.autoCommit = false
            try {
                connection.createStatement().use { statement ->
                    migration.statements.forEach(statement::execute)
                }
                connection.prepareStatement(
                    "INSERT INTO schema_migrations (version, applied_at_millis) VALUES (?, ?)"
                ).use { statement ->
                    statement.setInt(1, migration.version)
                    statement.setLong(2, System.currentTimeMillis())
                    statement.executeUpdate()
                }
                connection.commit()
            } catch (error: java.sql.SQLException) {
                connection.rollback()
                throw error
            } finally {
                connection.autoCommit = true
            }
        }
    }
}

fun jdbcConnection(
    jdbcUrl: String,
    username: String = "",
    password: String = ""
): Connection {
    return if (username.isBlank()) {
        DriverManager.getConnection(jdbcUrl)
    } else {
        DriverManager.getConnection(jdbcUrl, username, password)
    }
}

fun runBackendMigrations(
    jdbcUrl: String,
    username: String = "",
    password: String = ""
) {
    runMigrations(jdbcUrl, username, password, allBackendMigrations)
}

val allBackendMigrations = listOf(
    Migration(
        version = 1,
        statements = listOf(
            """
            CREATE TABLE account_users (
                phone VARCHAR(32) PRIMARY KEY,
                failed_login_count INTEGER NOT NULL,
                locked_until_millis BIGINT NOT NULL,
                deletion_requested_at_millis BIGINT,
                created_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            CREATE TABLE account_password_credentials (
                phone VARCHAR(32) PRIMARY KEY REFERENCES account_users(phone) ON DELETE CASCADE,
                password_salt TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                updated_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            CREATE TABLE account_sms_codes (
                phone VARCHAR(32) PRIMARY KEY,
                code VARCHAR(16) NOT NULL,
                expires_at_millis BIGINT NOT NULL,
                failed_attempts INTEGER NOT NULL,
                invalidated BOOLEAN NOT NULL,
                device_id TEXT NOT NULL,
                ip_address TEXT NOT NULL
            )
            """.trimIndent(),
            """
            CREATE TABLE account_sms_issues (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                scope_type VARCHAR(16) NOT NULL,
                scope_value TEXT NOT NULL,
                issued_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            CREATE INDEX account_sms_issues_scope_idx
            ON account_sms_issues(scope_type, scope_value, issued_at_millis)
            """.trimIndent(),
            """
            CREATE TABLE account_sessions (
                token TEXT PRIMARY KEY,
                phone VARCHAR(32) NOT NULL REFERENCES account_users(phone) ON DELETE CASCADE,
                device_id TEXT NOT NULL,
                issued_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            CREATE TABLE registered_devices (
                phone VARCHAR(32) NOT NULL REFERENCES account_users(phone) ON DELETE CASCADE,
                device_id TEXT NOT NULL,
                first_seen_at_millis BIGINT NOT NULL,
                last_seen_at_millis BIGINT NOT NULL,
                ip_address TEXT NOT NULL,
                PRIMARY KEY (phone, device_id)
            )
            """.trimIndent()
        )
    ),
    Migration(
        version = 2,
        statements = listOf(
            """
            CREATE TABLE IF NOT EXISTS cloud_config (
                phone VARCHAR(32) PRIMARY KEY REFERENCES account_users(phone) ON DELETE CASCADE,
                ai_consent_granted BOOLEAN NOT NULL DEFAULT FALSE,
                enhanced_context_granted BOOLEAN NOT NULL DEFAULT FALSE,
                feature_flags TEXT NOT NULL DEFAULT '{}',
                updated_at_millis BIGINT NOT NULL
            )
            """.trimIndent()
        )
    ),
    Migration(
        version = 3,
        statements = listOf(
            """
            CREATE TABLE IF NOT EXISTS ai_categorization_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                account_phone VARCHAR(32),
                merchant_title TEXT NOT NULL,
                source_label TEXT NOT NULL,
                transaction_kind TEXT NOT NULL,
                amount_range_label TEXT NOT NULL,
                suggested_category TEXT NOT NULL,
                confidence_label TEXT NOT NULL,
                explanation TEXT NOT NULL,
                created_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            CREATE INDEX IF NOT EXISTS ai_categorization_logs_phone_idx
            ON ai_categorization_logs(account_phone)
            """.trimIndent()
        )
    ),
    Migration(
        version = 4,
        statements = listOf(
            "DELETE FROM account_sms_codes",
            "DELETE FROM account_sessions",
            "ALTER TABLE account_sms_codes RENAME COLUMN code TO code_hash",
            "ALTER TABLE account_sms_codes ALTER COLUMN code_hash TYPE TEXT",
            "ALTER TABLE account_sessions RENAME COLUMN token TO token_hash"
        )
    ),
    Migration(
        version = 5,
        statements = listOf(
            """
            CREATE TABLE accounts (
                account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                legacy_phone VARCHAR(32),
                deletion_requested_at_millis BIGINT,
                created_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            INSERT INTO accounts (legacy_phone, deletion_requested_at_millis, created_at_millis)
            SELECT u.phone, u.deletion_requested_at_millis, u.created_at_millis
            FROM account_users u
            ORDER BY u.created_at_millis, u.phone
            """.trimIndent(),
            """
            CREATE TABLE account_phone_credentials (
                account_id BIGINT PRIMARY KEY REFERENCES accounts(account_id) ON DELETE CASCADE,
                phone VARCHAR(32) NOT NULL UNIQUE,
                password_salt TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                failed_login_count INTEGER NOT NULL DEFAULT 0,
                locked_until_millis BIGINT NOT NULL DEFAULT 0,
                updated_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            INSERT INTO account_phone_credentials (
                account_id, phone, password_salt, password_hash,
                failed_login_count, locked_until_millis, updated_at_millis
            )
            SELECT a.account_id, u.phone, c.password_salt, c.password_hash,
                   u.failed_login_count, u.locked_until_millis, c.updated_at_millis
            FROM account_users u
            JOIN accounts a ON a.legacy_phone = u.phone
            JOIN account_password_credentials c ON c.phone = u.phone
            """.trimIndent(),
            """
            CREATE TABLE account_wechat_identities (
                account_id BIGINT PRIMARY KEY REFERENCES accounts(account_id) ON DELETE CASCADE,
                app_id VARCHAR(64) NOT NULL,
                openid VARCHAR(64) NOT NULL,
                unionid VARCHAR(64),
                nickname TEXT,
                avatar_url TEXT,
                created_at_millis BIGINT NOT NULL,
                updated_at_millis BIGINT NOT NULL,
                CONSTRAINT uq_wechat_app_openid UNIQUE (app_id, openid),
                CONSTRAINT uq_wechat_unionid UNIQUE (unionid)
            )
            """.trimIndent(),
            """
            CREATE TABLE account_one_time_tickets (
                ticket_hash VARCHAR(64) PRIMARY KEY,
                ticket_type VARCHAR(32) NOT NULL,
                account_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
                payload_json TEXT NOT NULL,
                expires_at_millis BIGINT NOT NULL,
                used_at_millis BIGINT
            )
            """.trimIndent(),
            """
            CREATE TABLE account_sessions_v5 (
                token_hash TEXT PRIMARY KEY,
                account_id BIGINT NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
                device_id TEXT NOT NULL,
                issued_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            INSERT INTO account_sessions_v5 (token_hash, account_id, device_id, issued_at_millis)
            SELECT s.token_hash, a.account_id, s.device_id, s.issued_at_millis
            FROM account_sessions s
            JOIN accounts a ON a.legacy_phone = s.phone
            """.trimIndent(),
            """
            CREATE TABLE registered_devices_v5 (
                account_id BIGINT NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
                device_id TEXT NOT NULL,
                first_seen_at_millis BIGINT NOT NULL,
                last_seen_at_millis BIGINT NOT NULL,
                ip_address TEXT NOT NULL,
                PRIMARY KEY (account_id, device_id)
            )
            """.trimIndent(),
            """
            INSERT INTO registered_devices_v5 (account_id, device_id, first_seen_at_millis, last_seen_at_millis, ip_address)
            SELECT a.account_id, d.device_id, d.first_seen_at_millis, d.last_seen_at_millis, d.ip_address
            FROM registered_devices d
            JOIN accounts a ON a.legacy_phone = d.phone
            """.trimIndent(),
            """
            CREATE TABLE cloud_config_v5 (
                account_id BIGINT PRIMARY KEY REFERENCES accounts(account_id) ON DELETE CASCADE,
                ai_consent_granted BOOLEAN NOT NULL DEFAULT FALSE,
                enhanced_context_granted BOOLEAN NOT NULL DEFAULT FALSE,
                feature_flags TEXT NOT NULL DEFAULT '{}',
                updated_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            INSERT INTO cloud_config_v5 (account_id, ai_consent_granted, enhanced_context_granted, feature_flags, updated_at_millis)
            SELECT a.account_id, c.ai_consent_granted, c.enhanced_context_granted, c.feature_flags, c.updated_at_millis
            FROM cloud_config c
            JOIN accounts a ON a.legacy_phone = c.phone
            """.trimIndent(),
            """
            CREATE TABLE ai_categorization_logs_v5 (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                account_id BIGINT REFERENCES accounts(account_id) ON DELETE SET NULL,
                merchant_title TEXT NOT NULL,
                source_label TEXT NOT NULL,
                transaction_kind TEXT NOT NULL,
                amount_range_label TEXT NOT NULL,
                suggested_category TEXT NOT NULL,
                confidence_label TEXT NOT NULL,
                explanation TEXT NOT NULL,
                created_at_millis BIGINT NOT NULL
            )
            """.trimIndent(),
            """
            INSERT INTO ai_categorization_logs_v5 (
                id, account_id, merchant_title, source_label, transaction_kind,
                amount_range_label, suggested_category, confidence_label, explanation, created_at_millis
            )
            SELECT l.id, a.account_id, l.merchant_title, l.source_label, l.transaction_kind,
                   l.amount_range_label, l.suggested_category, l.confidence_label, l.explanation, l.created_at_millis
            FROM ai_categorization_logs l
            LEFT JOIN accounts a ON a.legacy_phone = l.account_phone
            """.trimIndent(),
            "DROP TABLE IF EXISTS account_sessions",
            "DROP TABLE IF EXISTS registered_devices",
            "DROP TABLE IF EXISTS cloud_config",
            "DROP TABLE IF EXISTS ai_categorization_logs",
            "DROP TABLE IF EXISTS account_password_credentials",
            "DROP TABLE IF EXISTS account_users",
            "ALTER TABLE account_sessions_v5 RENAME TO account_sessions",
            "ALTER TABLE registered_devices_v5 RENAME TO registered_devices",
            "ALTER TABLE cloud_config_v5 RENAME TO cloud_config",
            "ALTER TABLE ai_categorization_logs_v5 RENAME TO ai_categorization_logs",
            "CREATE INDEX ai_categorization_logs_account_id_idx ON ai_categorization_logs(account_id)",
            "ALTER TABLE accounts DROP COLUMN legacy_phone",
            "ALTER TABLE account_sms_codes ADD COLUMN purpose VARCHAR(32) NOT NULL DEFAULT 'DEFAULT'",
            "ALTER TABLE account_sms_codes ADD COLUMN context_key TEXT"
        )
    )
)
